export const TABLAS_EDITABLES: { tabla: string; titulo: string }[] = [
  { tabla: 'clientes', titulo: 'Clientes' },
  { tabla: 'comerciales', titulo: 'Comerciales' },
  { tabla: 'articulos', titulo: 'Artículos' },
  { tabla: 'familias_articulo', titulo: 'Familias de artículo' },
  { tabla: 'marcas', titulo: 'Marcas' },
  { tabla: 'canales', titulo: 'Canales' },
  { tabla: 'formatos_articulo', titulo: 'Formatos de artículo' },
  { tabla: 'proveedores', titulo: 'Proveedores' },
  { tabla: 'grupos_empresariales', titulo: 'Grupos empresariales' },
  { tabla: 'almacenes', titulo: 'Almacenes' },
  { tabla: 'facturas', titulo: 'Facturas' },
  { tabla: 'factura_lineas', titulo: 'Líneas de factura' },
  { tabla: 'pedidos', titulo: 'Pedidos' },
  { tabla: 'pedido_lineas', titulo: 'Líneas de pedido' },
  { tabla: 'pedido_modificaciones', titulo: 'Modificaciones de pedido' },
  { tabla: 'compras', titulo: 'Compras' },
  { tabla: 'compra_lineas', titulo: 'Líneas de compra' },
  { tabla: 'cobros', titulo: 'Cobros' },
  { tabla: 'incidencias', titulo: 'Incidencias' },
  { tabla: 'presupuesto', titulo: 'Presupuesto' },
  { tabla: 'stock_actual', titulo: 'Stock actual' },
  { tabla: 'stock_movimientos', titulo: 'Movimientos de stock' },
  { tabla: 'stock_en_transito', titulo: 'Stock en tránsito' },
  { tabla: 'alertas_config', titulo: 'Configuración de alertas' },
  { tabla: 'alertas_generadas', titulo: 'Alertas generadas' },
  { tabla: 'marketing_canales', titulo: 'Canales de marketing' },
  { tabla: 'marketing_inversion', titulo: 'Inversión de marketing' },
  { tabla: 'ventas_semanales', titulo: 'Ventas semanales' },
  { tabla: 'financiero_cuentas_anuales', titulo: 'Cuentas anuales (financiero)' },
  { tabla: 'financiero_kpis', titulo: 'KPIs financieros' },
];